apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: vihanduk/auth-service
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: MONGO_URI
              value: mongodb+srv://vihanduk:vinu@f-deli.arknvgo.mongodb.net/
            - name: JWT_SECRET
              value: 1f48fbd0c4d54d82a61b2de43606ae88ef8d9d92a21560a3d8df3bb2a985e4f2
